services:
  app:
    build: .
    ports:
      - '5000:3000'
    environment:
      POSTGRES_URL: postgresql://postgres:postgres@db:5432/svelte
    depends_on:
      - db

  db:
    image: postgres:18-alpine3.23
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: svelte
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
